SERVER:
  GRPC:
    PORT: 14443
  HTTP:
    PORT: 14080

LOG:
  LEVEL: DEBUG
  MODE: development

MIGRATION_FOLDER: file://sql/migrations

POSTGRESQL:
  HOST: 127.0.0.1
  PORT: 5433
  USERNAME: cdp_service
  PASSWORD: postgres
  DATABASE: cdp_service

AIRFLOW_ADAPTER_CONFIG:
  ADDRESS: https://c275-113-161-84-248.ngrok-free.app
  USERNAME: airflow
  PASSWORD: airflow

QUERY_ADAPTER_CONFIG:
  ADDRESS: http://103.109.43.33

MQQT_ADAPTAER_CONFIG:
  HOST: localhost
  PORT: 1883
  CLIENT_ID: "go_mqtt_client"
  USERNAME: "apcs-thesis-cdp"
  PASSWORD: "secret"