SERVER:
  GRPC:
    PORT: 14443
  HTTP:
    PORT: 14080

LOG:
  LEVEL: DEBUG
  MODE: development

MIGRATION_FOLDER: file://sql/migrations

POSTGRESQL:
  HOST: postgres.backend.orb.local
  PORT: 5432
  USERNAME: cdp_service
  PASSWORD: postgres
  DATABASE: cdp_service