version: '3.1'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: cdp_service
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cdp_service
