name: CD Pipeline

on:
  workflow_run:
    workflows: ["GoBuild"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull phat12a/backend:main
    - name: Delete Old docker container
      run: sudo docker rm -f backend-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 11080:11080 --name backend-container phat12a/backend:main
      
